[workspace]
authors = ["mathias157 <mathiasros@proton.me>"]
channels = ["conda-forge"]
name = "BALMOREL"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
analyse = "python analysis/analyse.py "
verify = "python analysis/verify.py "
sync-down = "rsync -avzu --filter=':- .gitignore' mberos@transfer.gbar.dtu.dk:/work3/mberos/Balmorel/ ."
sync-up = "rsync -avzu --filter=':- .gitignore'  ./ mberos@transfer.gbar.dtu.dk:/work3/mberos/Balmorel"
sync-plots = "rsync -avzu mberos@transfer.gbar.dtu.dk:'/work3/mberos/Balmorel/analysis/plots/collected*.pdf' analysis/plots/"
sync-scenario = "rsync -avzu mberos@transfer.gbar.dtu.dk:'/work3/mberos/Balmorel/analysis/plots/collected*.pdf' analysis/plots/"

[tasks.sync-mainresult]
args = ["scenario", {arg="suffix", default="*"}]
cmd = "rsync -avzu mberos@transfer.gbar.dtu.dk:'/work3/mberos/Balmorel/{{ scenario }}/model/MainResults{{ suffix }}.gdx' {{ scenario }}/model/"

[dependencies]
premailer = ">=3.10.0,<4"
click = ">=8.3.1,<9"
python-decouple = ">=3.8,<4"
python = ">=3.14.3,<3.15"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.1,<4"
numpy = ">=2.4.3,<3"

[pypi-dependencies]
pybalmorel = ">=1.1.2, <2"
tsam = ">=2.3.9, <3"
ripgrepy = ">=2.2.0, <3"
